# Generated by Django 5.0.6 on 2024-07-08 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], max_length=3)),
                ('work_start', models.TimeField()),
                ('work_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalStaff',
            fields=[
                ('medicalStaff_id', models.AutoField(primary_key=True, serialize=False)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ManyToManyField(related_name='medical_schedule', to='staff.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='AssistantStaff',
            fields=[
                ('Assistant_id', models.AutoField(primary_key=True, serialize=False)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marital_status', models.CharField(choices=[('sgl', 'Single'), ('marr', 'Married')], max_length=4)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ManyToManyField(related_name='assistant_schedule', to='staff.schedule')),
            ],
        ),
    ]
