# Generated by Django 5.0.6 on 2024-07-08 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication', '0001_initial'),
        ('services', '0001_initial'),
        ('staff', '0001_initial'),
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startexamination',
            name='assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.assistantstaff'),
        ),
        migrations.AddField(
            model_name='startexamination',
            name='medical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.medicalstaff'),
        ),
        migrations.AddField(
            model_name='startexamination',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.patient'),
        ),
        migrations.AddField(
            model_name='startexamination',
            name='queue',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='communication.queue'),
        ),
        migrations.AddField(
            model_name='examination',
            name='start_examination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.startexamination'),
        ),
        migrations.AddField(
            model_name='startexamination',
            name='type_examination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.typeexamination'),
        ),
    ]
