# Generated by Django 5.0.6 on 2024-07-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_startexamination_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startexamination',
            name='pay',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
