# Generated by Django 5.0.6 on 2024-07-08 20:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('queue_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.TimeField(null=True)),
                ('activate_assistant', models.BooleanField(default=False)),
                ('activate_doctor', models.BooleanField(default=False)),
                ('end_work', models.BooleanField(default=False)),
            ],
        ),
    ]
